import { AbsoluteFill, Audio, Img, interpolate, staticFile, useCurrentFrame } from "remotion";

const ink = "#15121f";
const paper = "#f7f6fb";
const purple = "#7959f5";
const violet = "#b980ff";
const mint = "#c7ff68";
const coral = "#ff786a";
const blue = "#75b6ff";

const scene = (frame: number, start: number, end: number) => interpolate(frame, [start, start + 12, end - 12, end], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
const enter = (frame: number, start: number) => interpolate(frame, [start, start + 16], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
const inScale = (frame: number, start: number) => interpolate(frame, [start, start + 16], [0.9, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

const Label: React.FC<{ children: React.ReactNode; color?: string }> = ({ children, color = purple }) => <div style={{ color, fontSize: 24, fontWeight: 900, letterSpacing: "0.14em", textTransform: "uppercase" }}>{children}</div>;

const FloatingDot: React.FC<{ frame: number; x: number; y: number; size: number; color: string; delay?: number }> = ({ frame, x, y, size, color, delay = 0 }) => <div style={{ position: "absolute", left: x, top: y, width: size, height: size, borderRadius: 999, background: color, opacity: 0.8, scale: interpolate(frame, [delay, delay + 70, 2250], [0.6, 1.12, 0.76], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }), translate: `0 ${Math.sin((frame + delay) / 38) * 15}px`, filter: "blur(0.4px)" }} />;

const ProductWindow: React.FC<{ file: string; label: string; frame: number; start: number; end: number; width: number; rotate?: number; x?: number; y?: number }> = ({ file, label, frame, start, end, width, rotate = 0, x = 0, y = 0 }) => <div style={{ position: "absolute", left: x, top: y, width, opacity: scene(frame, start, end), scale: inScale(frame, start), rotate: `${rotate + interpolate(frame, [start, end], [4, -4], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })}deg`, boxShadow: "0 40px 100px rgba(42, 20, 77, 0.27)", border: "1px solid rgba(38, 25, 58, 0.15)", overflow: "hidden", borderRadius: 32, background: "#15243b" }}>
  <div style={{ height: 56, display: "flex", alignItems: "center", gap: 10, padding: "0 23px", background: "#f7f6fb", color: ink, fontSize: 20, fontWeight: 800 }}><span style={{ width: 12, height: 12, background: coral, borderRadius: 99 }} /><span style={{ width: 12, height: 12, background: "#ffc956", borderRadius: 99 }} /><span style={{ width: 12, height: 12, background: mint, borderRadius: 99 }} /><span style={{ marginLeft: 12 }}>{label}</span></div>
  <Img src={staticFile(`screens/${file}`)} style={{ width: "100%", display: "block" }} />
</div>;

const Pointer: React.FC<{ frame: number; start: number; x: number; y: number }> = ({ frame, start, x, y }) => <div style={{ position: "absolute", left: x, top: y, opacity: enter(frame, start), scale: inScale(frame, start), fontSize: 64, lineHeight: 1, color: ink, textShadow: "0 7px 12px rgba(0,0,0,0.18)", rotate: "-18deg", zIndex: 10 }}>☝</div>;

const Pill: React.FC<{ children: React.ReactNode; color?: string; text?: string }> = ({ children, color = mint, text = ink }) => <div style={{ display: "inline-flex", alignItems: "center", padding: "14px 20px", borderRadius: 999, background: color, color: text, fontSize: 23, fontWeight: 900, letterSpacing: "0.04em" }}>{children}</div>;

export const BranchlineDemo: React.FC = () => {
  const frame = useCurrentFrame();
  const hook = scene(frame, 0, 210);
  const contract = scene(frame, 150, 450);
  const evidence = scene(frame, 390, 690);
  const rehearsal = scene(frame, 630, 990);
  const council = scene(frame, 930, 1350);
  const decision = scene(frame, 1290, 1680);
  const policy = scene(frame, 1620, 1950);
  const harness = scene(frame, 1890, 2130);
  const finale = scene(frame, 2070, 2250);

  return <AbsoluteFill style={{ background: paper, color: ink, fontFamily: "Aptos Display, Inter, Arial, sans-serif", overflow: "hidden" }}>
    <Audio src={staticFile("bed.wav")} volume={0.36} />
    <Audio src={staticFile("narration.wav")} volume={1} />
    <div style={{ position: "absolute", inset: 0, background: "radial-gradient(circle at 73% 18%, rgba(184,128,255,0.68), transparent 25%), radial-gradient(circle at 17% 80%, rgba(199,255,104,0.63), transparent 28%), radial-gradient(circle at 76% 86%, rgba(117,182,255,0.46), transparent 24%)" }} />
    <FloatingDot frame={frame} x={120} y={190} size={18} color={purple} delay={0} /><FloatingDot frame={frame} x={1740} y={290} size={30} color={mint} delay={200} /><FloatingDot frame={frame} x={1540} y={810} size={24} color={coral} delay={420} />
    <div style={{ position: "absolute", top: 56, left: 70, display: "flex", alignItems: "center", gap: 13, zIndex: 20 }}><div style={{ width: 33, height: 33, borderRadius: 11, background: ink }} /><div style={{ fontWeight: 950, fontSize: 26, letterSpacing: "0.08em" }}>BRANCHLINE</div></div>
    <div style={{ position: "absolute", top: 60, right: 70, fontSize: 20, fontWeight: 800, letterSpacing: "0.1em", color: "rgba(21,18,31,0.58)" }}>RELEASE REHEARSAL</div>

    <div style={{ position: "absolute", inset: 0, opacity: hook, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ width: 1450, textAlign: "center" }}><Label>Before it ships.</Label><div style={{ fontSize: 137, letterSpacing: "-0.075em", fontWeight: 950, lineHeight: 0.91, marginTop: 30 }}>Rehearse the<br /><span style={{ color: purple }}>release.</span></div><div style={{ fontSize: 37, fontWeight: 650, marginTop: 34, color: "rgba(21,18,31,0.64)" }}>A product demo about seeing the path before it breaks.</div><div style={{ display: "flex", justifyContent: "center", gap: 14, marginTop: 48 }}><Pill>REAL GIT</Pill><Pill color={purple} text={paper}>DETERMINISTIC</Pill><Pill color={ink} text={paper}>HUMAN-OWNED</Pill></div></div></div>

    <div style={{ position: "absolute", inset: 0, opacity: contract, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ width: 1480, display: "grid", gridTemplateColumns: "0.9fr 1.1fr", alignItems: "center", gap: 120 }}><div><Label color={coral}>A small diff. A big risk.</Label><div style={{ fontSize: 91, fontWeight: 950, letterSpacing: "-0.065em", lineHeight: 0.97, marginTop: 24 }}>One field<br />changes the<br /><span style={{ color: coral }}>release.</span></div><div style={{ marginTop: 32, fontSize: 31, color: "rgba(21,18,31,0.64)", lineHeight: 1.32 }}>A required response field can leave a legacy client behind.</div></div><div style={{ padding: 45, borderRadius: 34, background: ink, color: paper, boxShadow: "0 35px 80px rgba(46,20,70,0.22)", scale: inScale(frame, 150), rotate: "-3deg" }}><div style={{ fontSize: 22, color: "rgba(247,246,251,0.52)", fontFamily: "Cascadia Code, Consolas, monospace" }}>release-risk.ts</div><div style={{ marginTop: 37, fontFamily: "Cascadia Code, Consolas, monospace", fontSize: 38, lineHeight: 1.7 }}><div style={{ color: "rgba(247,246,251,0.52)" }}>interface ReleaseRisk {'{'}</div><div style={{ color: coral, marginLeft: 38 }}>− riskLevel?: string</div><div style={{ color: mint, marginLeft: 38 }}>+ riskLevel: string</div><div style={{ color: "rgba(247,246,251,0.52)" }}>{'}'}</div></div><div style={{ marginTop: 22 }}><Pill color={mint}>CONTRACT TIGHTENED</Pill></div></div></div></div>

    <div style={{ position: "absolute", inset: 0, opacity: evidence }}><div style={{ position: "absolute", top: 158, left: 155 }}><Label>Map the real change</Label><div style={{ fontSize: 77, fontWeight: 950, letterSpacing: "-0.06em", marginTop: 16 }}>Follow the evidence.</div></div><ProductWindow file="impact.png" label="Branchline impact map" frame={frame} start={390} end={690} width={1040} x={500} y={268} rotate={-2} /><div style={{ position: "absolute", left: 118, top: 464, opacity: enter(frame, 455), scale: inScale(frame, 455) }}><Pill color={mint}>CONTRACT</Pill><div style={{ width: 300, height: 5, background: mint, marginTop: 14, rotate: "-13deg", transformOrigin: "left" }} /></div><div style={{ position: "absolute", right: 102, top: 560, opacity: enter(frame, 490), scale: inScale(frame, 490) }}><Pill color={purple} text={paper}>LEGACY CLIENT</Pill><div style={{ width: 255, height: 5, background: purple, marginTop: 14, rotate: "158deg", transformOrigin: "right" }} /></div><Pointer frame={frame} start={530} x={1245} y={570} /></div>

    <div style={{ position: "absolute", inset: 0, opacity: rehearsal }}><div style={{ position: "absolute", top: 145, left: 155 }}><Label color={purple}>Play the release</Label><div style={{ fontSize: 76, fontWeight: 950, letterSpacing: "-0.06em", marginTop: 15 }}>Test the safer move.</div></div><ProductWindow file="rehearse.png" label="Deterministic rehearsal" frame={frame} start={630} end={990} width={1000} x={115} y={313} rotate={2} /><div style={{ position: "absolute", right: 120, top: 280, width: 560, display: "flex", flexDirection: "column", gap: 17 }}><div style={{ opacity: enter(frame, 705), scale: inScale(frame, 705), padding: "23px 28px", borderRadius: 22, background: coral, color: ink, fontSize: 34, fontWeight: 950 }}>FULL ROLLOUT <span style={{ float: "right" }}>71% error</span></div><div style={{ opacity: enter(frame, 745), scale: inScale(frame, 745), padding: "23px 28px", borderRadius: 22, background: mint, color: ink, fontSize: 34, fontWeight: 950 }}>CANARY + ADAPTER <span style={{ float: "right" }}>observe</span></div><div style={{ opacity: enter(frame, 785), scale: inScale(frame, 785), padding: "23px 28px", borderRadius: 22, background: ink, color: paper, fontSize: 29, fontWeight: 850 }}>REHEARSE. BRANCH. COMPARE.</div></div><Pointer frame={frame} start={820} x={738} y={716} /></div>

    <div style={{ position: "absolute", inset: 0, opacity: council }}><div style={{ position: "absolute", top: 140, left: 155 }}><Label color={purple}>Challenge the path</Label><div style={{ fontSize: 76, fontWeight: 950, letterSpacing: "-0.06em", marginTop: 15 }}>One packet.<br />Every lens.</div></div><ProductWindow file="council.png" label="Evidence-bound Council" frame={frame} start={930} end={1350} width={950} x={820} y={214} rotate={2} /><div style={{ position: "absolute", left: 130, top: 455, display: "flex", flexDirection: "column", gap: 14 }}>{[["CONTRACT", mint], ["TEST + OBS", blue], ["ROLLOUT", violet], ["SECURITY", coral]].map(([name, color], index) => <div key={name as string} style={{ opacity: enter(frame, 1000 + index * 28), scale: inScale(frame, 1000 + index * 28), width: 360, padding: "19px 24px", background: color as string, borderRadius: 18, fontWeight: 950, fontSize: 30, boxShadow: "0 14px 26px rgba(45,22,73,0.12)" }}>{name as string}</div>)}</div><div style={{ position: "absolute", right: 110, top: 755, opacity: enter(frame, 1150), padding: "18px 21px", color: paper, background: ink, borderRadius: 18, fontFamily: "Cascadia Code, Consolas, monospace", fontWeight: 800, fontSize: 23 }}>HASH BOUND · CLAIM VALIDATED</div></div>

    <div style={{ position: "absolute", inset: 0, opacity: decision }}><div style={{ position: "absolute", top: 145, right: 155, width: 640 }}><Label color={coral}>Accountability stays visible</Label><div style={{ fontSize: 78, fontWeight: 950, letterSpacing: "-0.065em", lineHeight: 0.95, marginTop: 18 }}>Agents advise.<br /><span style={{ color: coral }}>Humans decide.</span></div><div style={{ marginTop: 31, fontSize: 31, lineHeight: 1.3, color: "rgba(21,18,31,0.64)" }}>Every rationale, follow-up, and disagreement remains in the release ledger.</div><div style={{ marginTop: 34 }}><Pill color={coral}>ACCEPTED RISK · ACCOUNTABLE</Pill></div></div><ProductWindow file="decision.png" label="Human decision ledger" frame={frame} start={1290} end={1680} width={1110} x={85} y={252} rotate={-2} /><Pointer frame={frame} start={1460} x={951} y={628} /></div>

    <div style={{ position: "absolute", inset: 0, opacity: policy, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ width: 1480, display: "grid", gridTemplateColumns: "0.95fr 1.05fr", gap: 100, alignItems: "center" }}><div><Label color={purple}>Make the standard executable</Label><div style={{ fontSize: 86, lineHeight: 0.96, fontWeight: 950, letterSpacing: "-0.065em", marginTop: 22 }}>Enforce<br />the <span style={{ color: purple }}>proof.</span></div><div style={{ fontSize: 31, lineHeight: 1.3, color: "rgba(21,18,31,0.64)", marginTop: 28 }}>Policy gates move the same release evidence into local development and CI.</div></div><div style={{ borderRadius: 30, overflow: "hidden", background: ink, color: paper, padding: 44, boxShadow: "0 40px 90px rgba(44,22,75,0.25)", scale: inScale(frame, 1620), fontFamily: "Cascadia Code, Consolas, monospace" }}><div style={{ color: "rgba(247,246,251,0.48)", fontSize: 22 }}>.branchline/policy.yml</div><div style={{ marginTop: 26, fontSize: 28, lineHeight: 1.74 }}><div>requireCouncil: <span style={{ color: mint }}>true</span></div><div>requireHumanDecision: <span style={{ color: mint }}>true</span></div><div>minTestConfidence: <span style={{ color: "#ffc956" }}>75</span></div><div style={{ marginTop: 26, display: "inline-block", padding: "13px 18px", background: mint, color: ink, borderRadius: 12, fontWeight: 950 }}>✓ POLICY PASSED</div></div></div></div></div>

    <div style={{ position: "absolute", inset: 0, opacity: harness, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ width: 1460, textAlign: "center" }}><Label>One source of truth</Label><div style={{ fontSize: 98, fontWeight: 950, letterSpacing: "-0.07em", lineHeight: 0.94, marginTop: 22 }}>Every harness<br /><span style={{ color: purple }}>gets the proof.</span></div><div style={{ margin: "44px auto 0", padding: "25px 30px", width: 1120, borderRadius: 25, background: ink, color: paper, textAlign: "left", fontFamily: "Cascadia Code, Consolas, monospace", fontSize: 30, boxShadow: "0 35px 90px rgba(44,22,75,0.24)" }}><span style={{ color: mint }}>$</span> npx github:KrisnaSantosa15/branchline mcp<div style={{ color: "rgba(247,246,251,0.55)", fontSize: 22, marginTop: 16 }}>analyze_release · get_evidence_pack · compare_rollouts · check_policy</div></div><div style={{ display: "flex", justifyContent: "center", gap: 14, marginTop: 30 }}>{["CODEX", "CLAUDE", "CURSOR", "COPILOT", "OPENCODE", "GEMINI"].map((item, index) => <div key={item} style={{ opacity: enter(frame, 1940 + index * 18), padding: "12px 17px", borderRadius: 12, background: "rgba(21,18,31,0.09)", fontSize: 19, fontWeight: 900 }}>{item}</div>)}</div></div></div>

    <div style={{ position: "absolute", inset: 0, opacity: finale, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ textAlign: "center" }}><div style={{ width: 84, height: 84, borderRadius: 28, background: mint, margin: "0 auto", boxShadow: "0 22px 52px rgba(119,88,245,0.25)" }} /><div style={{ fontSize: 112, fontWeight: 950, letterSpacing: "-0.075em", lineHeight: 0.92, marginTop: 28 }}>Map it.<br /><span style={{ color: purple }}>Rehearse it.</span><br />Then decide.</div><div style={{ marginTop: 30, fontSize: 28, color: "rgba(21,18,31,0.58)", fontWeight: 700 }}>BRANCHLINE · EVIDENCE-LED RELEASE REHEARSAL</div></div></div>
  </AbsoluteFill>;
};
